'use strict';
// ════════════════════════════════════════════════════════
//  DOC EXTRACTION — derive MAP.md and the ARCHITECTURE.md
//  table of contents from the sources themselves. Shared by
//  build-map.js (writes them) and tests/docs.spec.js (fails
//  when they drift) so there is exactly ONE definition of
//  "what a section is".
//
//  Nothing here is a build step for the app: the outputs are
//  committed, and app.js is served as-is.
// ════════════════════════════════════════════════════════

const RULE = /^\s*\/\/ ═+\s*$/;
const COMMENT = /^\s*\/\/\s?(.*)$/;

const TOC_START = '<!-- toc:start -->';
const TOC_END = '<!-- toc:end -->';

const GENERATED = (script) =>
  `<!-- GENERATED by tools/${script} — do not edit by hand.\n` +
  `     Run \`npm run map\` after adding, removing or retitling a section;\n` +
  `     \`npm run test:docs\` fails while this file is stale. -->`;

// ── app.js section banners ──────────────────────────────
// A banner is a ═ rule, one or more // comment lines, then a closing rule.
// The first comment line is the title; the rest is its blurb. The title's
// name half (before the em dash) is what MAP.md tells readers to grep.
function sections(src) {
  const lines = src.split('\n');

  // An unclosed banner would flip the open/closed state for the rest of the
  // file and quietly swallow every later section, so refuse to guess.
  const rules = lines.filter((l) => RULE.test(l)).length;
  if (rules % 2 !== 0) {
    throw new Error(
      `app.js has ${rules} banner rule lines (odd) — a section banner is missing its closing ═ rule`
    );
  }

  const out = [];
  let open = false;
  let buf = [];
  for (const line of lines) {
    if (RULE.test(line)) {
      if (open && buf.length) out.push(toSection(buf));
      open = !open;
      buf = [];
      continue;
    }
    if (!open) continue;
    const m = COMMENT.exec(line);
    if (m) buf.push(m[1].trim());
  }
  return out;
}

function toSection(buf) {
  const title = buf[0];
  const dash = title.indexOf(' — ');
  const name = (dash === -1 ? title : title.slice(0, dash)).trim();
  const head = dash === -1 ? '' : title.slice(dash + 3);
  const blurb = [head, ...buf.slice(1)]
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
  return { name, marker: `//  ${name}`, blurb };
}

// MAP.md points at code by grepping `//  NAME`. That contract holds only
// while each marker resolves to exactly one line — an added `IMAGE NODES`
// beside `IMAGE NODE` would send readers to the wrong section with no error.
// Returns a list of human-readable problems (empty = contract intact).
function markerProblems(src, secs) {
  const lines = src.split('\n');
  const problems = [];
  const seen = new Set();
  for (const s of secs) {
    if (seen.has(s.name)) problems.push(`duplicate section title: "${s.name}"`);
    seen.add(s.name);
    const hits = lines.filter((l) => l.includes(s.marker)).length;
    if (hits !== 1) {
      problems.push(`marker "${s.marker}" matches ${hits} lines (must be exactly 1)`);
    }
  }
  return [...new Set(problems)]; // a repeated title reports the same marker twice
}

// Banners run from one line to several paragraphs, but the map only has to
// answer "is this the section I want?" — the full reasoning stays in the code
// and in ARCHITECTURE.md. Take the first sentence, plus a second if the first
// is too short to be informative, and hard-cap the result.
const GIST_MIN = 80;
const GIST_MAX = 240;

function gist(blurb) {
  if (!blurb) return '—';
  const sentences = blurb.split(/(?<=\.)\s+/);
  let out = sentences[0];
  if (out.length < GIST_MIN && sentences[1]) out += ' ' + sentences[1];
  if (out.length > GIST_MAX) {
    const cut = out.slice(0, GIST_MAX);
    out = cut.slice(0, cut.lastIndexOf(' ')) + '…';
  }
  return out;
}

// Deliberately no line numbers: they shift on every edit above a section, so
// storing them would churn this file in nearly every commit and be stale in
// between. A grep marker changes only when a section really changes.
function renderMap(secs) {
  const rows = secs.map((s) => `| \`${s.marker}\` | ${gist(s.blurb).replace(/\|/g, '\\|')} |`);
  return [
    GENERATED('build-map.js'),
    '',
    '# Map of `app.js`',
    '',
    '`app.js` is one IIFE split by section banners. Rather than reading it end',
    'to end, jump to a section by grepping its marker — each one matches exactly',
    'one line, and `npm run test:docs` fails if that ever stops being true:',
    '',
    '```sh',
    "grep -n '//  PORTS' app.js",
    '```',
    '',
    `Sections in file order (${secs.length} total). See ARCHITECTURE.md for the`,
    'invariants behind them — this file only says *where* things are.',
    '',
    '| Grep for | What the section covers |',
    '| --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

// ── ARCHITECTURE.md table of contents ───────────────────
function headings(md) {
  const out = [];
  let fenced = false;
  for (const line of md.split('\n')) {
    if (/^\s*```/.test(line)) {
      fenced = !fenced;
      continue;
    }
    if (fenced) continue; // a #-comment inside a code block is not a heading
    const m = /^(#{2,3}) +(.+?)\s*$/.exec(line);
    if (m) out.push({ depth: m[1].length, text: m[2] });
  }
  return out;
}

// github-slugger's rules: lowercase, drop punctuation, then map each space to
// ONE hyphen — runs are not collapsed, so a symbol dropped from between two
// words (`whiteboard` → `assets`) leaves a double hyphen in the real anchor.
// Emulated from its documented behaviour, not verified against the renderer.
function anchor(text, used) {
  const base = text
    .toLowerCase()
    .replace(/[^\w\- ]+/g, '')
    .trim()
    .replace(/ /g, '-');
  let slug = base;
  let n = 1;
  while (used.has(slug)) slug = `${base}-${n++}`;
  used.add(slug);
  return slug;
}

function renderToc(hs) {
  const used = new Set();
  const lines = hs.map((h) => {
    const indent = h.depth === 2 ? '' : '  ';
    // strip markdown code ticks from the label; keep the words
    const label = h.text.replace(/`/g, '');
    return `${indent}- [${label}](#${anchor(h.text, used)})`;
  });
  return ['**Contents**', '', ...lines].join('\n');
}

function injectToc(md, toc) {
  const i = md.indexOf(TOC_START);
  const j = md.indexOf(TOC_END);
  if (i === -1 || j === -1) {
    throw new Error(`ARCHITECTURE.md is missing its ${TOC_START} / ${TOC_END} markers`);
  }
  if (j < i) throw new Error(`ARCHITECTURE.md has ${TOC_END} before ${TOC_START}`);
  return md.slice(0, i + TOC_START.length) + '\n' + toc + '\n' + md.slice(j);
}

module.exports = {
  sections,
  markerProblems,
  renderMap,
  headings,
  renderToc,
  injectToc,
  TOC_START,
  TOC_END,
};
